/*
** EPITECH PROJECT, 2019
** MUL_my_rpg_2019
** File description:
** rpg.h
*/

#include <time.h>
#include <SFML/Window.h>
#include <SFML/System.h>
#include <SFML/Graphics.h>
#include <SFML/Audio.h>

typedef struct rpg
{
    sfTexture *texture_logoa;
    sfTexture *texture_logo;
    sfTexture *texture_play;
    sfTexture *texture_fontprcpl;
    sfTexture *texture_quit;
    sfTexture *texture_cursor;
    sfTexture *texture_play_surbr;
    sfTexture *texture_quit_surbr;
    sfTexture *texture_map_gauche;
    sfTexture *texture_map_milieu;
    sfTexture *texture_map_droite;
    sfTexture *texture_cursor_game;
    sfTexture*texture_minipap_gauche;
    sfTexture*texture_minipap_droite;
    sfTexture*texture_minipap_milieu;
    sfTexture *texture_map_gauche_cinematique;
    sfTexture *texture_map_milieu_cinematique;
    sfTexture *texture_map_droite_cinematique;
    sfTexture *texture_settings;
    sfTexture *texture_menu;
    sfTexture *texture_quit_game;
    sfSprite *sprite_cursor_game;
    sfSprite *sprite_logoa;
    sfSprite *sprite_logo;
    sfSprite *sprite_play;
    sfSprite *sprite_quit;
    sfSprite *sprite_font_prcpl;
    sfSprite *sprite_play_surbr;
    sfSprite *sprite_quit_surbr;
    sfSprite *sprite_cursor;
    sfSprite *sprite_map_gauche;
    sfSprite *sprite_map_milieu;
    sfSprite *sprite_map_droite;
    sfSprite *sprite_minimap_gauche;
    sfSprite *sprite_minimap_milieu;
    sfSprite *sprite_minimap_droite;
    sfSprite *sprite_map_gauche_cinematique;
    sfSprite *sprite_map_milieu_cinematique;
    sfSprite *sprite_map_droite_cinematique;
    sfSprite *sprite_settings;
    sfSprite *sprite_quit_set;
    sfSprite *sprite_menu;
    sfVector2f pos_logoa;
    sfVector2f pos_logo;
    sfVector2f pos_play;
    sfVector2f pos_quit;
    sfVector2f pos_font_prcpl;
    sfVector2f pos_cursor;
    sfVector2f pos_play_surbr;
    sfVector2f pos_quit_surbr;
    sfVector2f pos_map_gauche;
    sfVector2f pos_map_milieu;
    sfVector2f pos_map_droite;
    sfVector2f pos_cursor_game;
    sfVector2f pos_minimapgauche;
    sfVector2f pos_minimapmilieu;
    sfVector2f pos_minimapdroite;
    sfVector2f pos_map_gauche_cinematique;
    sfVector2f pos_map_milieu_cinematique;
    sfVector2f pos_map_droite_cinematique;
    sfVector2f pos_menu_set;
    sfVector2f pos_play_set;
    sfVector2f pos_quit_set;
    sfIntRect rect_logo;
    sfClock *clock_prcpl;
    sfTime time_prcpl;
    float sec_prcpl;
    sfVector2i mouse;
}prcpl;

typedef struct rpg2
{
    sfRenderWindow *window;
    sfVideoMode pixels;
    sfEvent event;
    int die;
    int i;
    int right;
    int left;
    int front;
    int back;
    int attack_r;
    int attack_l;
    int attack_fr;
    int attack_b;
    int bomb_r;
    int bomb_l;
    int bomb_fr;
    int bomb_b;
    int die_link;
    int die_link_2;
    int die_link_3;
    int die_link_4;
    int die_link_5;
    int die_link_6;
    int die_link_7;
    int die_link_8;
    int die_link_9;
    int die_link_10;
    int die_alien;
    int die_alien_2;
    int die_alien_3;
    int die_alien_4;
    int die_alien_5;
    int die_alien_6;
    int die_alien_7;
    int die_alien_8;
    int die_alien_9;
    int die_alien_10;
}display;

typedef struct rpg3
{
    sfSprite *sprite_mvright;
    sfSprite *sprite_mvleft;
    sfSprite *sprite_mvfont;
    sfSprite *sprite_mvback;
    sfSprite *sprite_linkspawn;
    sfSprite *sprite_linkspawn_2;
    sfSprite *sprite_atck_right;
    sfSprite *sprite_atck_left;
    sfSprite *sprite_atck_front;
    sfSprite *sprite_atck_back;
    sfSprite *sprite_redcircle;
    sfSprite *sprite_fond_noir;
    sfTexture *texture_mvright;
    sfTexture *texture_mvleft;
    sfTexture *texture_mvfont;
    sfTexture *texture_mvback;
    sfTexture *texture_linkspawn;
    sfTexture *texture_redcircle;
    sfTexture *texture_atck_right;
    sfTexture *texture_atck_left;
    sfTexture *texture_atck_front;
    sfTexture *texture_atck_back;
    sfTexture *texture_fond_noir;
    sfVector2f pos_mvright;
    sfVector2f pos_mvleft;
    sfVector2f pos_mvfont;
    sfVector2f pos_mvback;
    sfVector2f pos_a_right;
    sfVector2f pos_a_left;
    sfVector2f pos_a_front;
    sfVector2f pos_a_back;
    sfVector2f pos_link_spawn;
    sfVector2f pos_link_spawn_2;
    sfVector2f pos_redcircle;
    sfVector2f pos_fond_noir;
    sfIntRect rect_mvright;
    sfIntRect rect_mvleft;
    sfIntRect rect_mvfont;
    sfIntRect rect_mvback;
    sfIntRect rect_a_right;
    sfIntRect rect_a_left;
    sfIntRect rect_a_front;
    sfIntRect rect_a_back;
    sfClock *clock_mvright;
    sfClock *clock_mvleft;
    sfClock *clock_mvfont;
    sfClock *clock_mvback;
    sfClock *clock_a_right;
    sfClock *clock_a_left;
    sfClock *clock_a_front;
    sfClock *clock_a_back;
    float sec_mvright;
    float sec_mvleft;
    float sec_mvfont;
    float sec_mvback;
    float sec_a_right;
    float sec_a_left;
    float sec_a_front;
    float sec_a_back;
    sfTime time_mvright;
    sfTime time_mvleft;
    sfTime time_mvfont;
    sfTime time_mvback;
    sfTime time_a_right;
    sfTime time_a_left;
    sfTime time_a_front;
    sfTime time_a_back;
}move_p;

typedef struct rpg4
{
    sfSprite *sprite_bombattack;
    sfSprite *sprite_bombattack_2;
    sfSprite *sprite_bombattack_3;
    sfSprite *sprite_bombattack_4;
    sfSprite *sprite_bombattack_5;
    sfSprite *sprite_bombattack_6;
    sfSprite *sprite_bombattack_7;
    sfSprite *sprite_bombattack_8;
    sfSprite *sprite_alien;
    sfSprite *sprite_alien_2;
    sfSprite *sprite_alien_3;
    sfSprite *sprite_alien_4;
    sfSprite *sprite_alien_5;
    sfSprite *sprite_alien_6;
    sfSprite *sprite_alien_7;
    sfSprite *sprite_alien_8;
    sfSprite *sprite_alien_9;
    sfSprite *sprite_alien_10;
    sfSprite *sprite_cinem1;
    sfSprite *sprite_cinem2;
    sfSprite *sprite_cinem3;
    sfSprite *sprite_zelda;
    sfSprite *sprite_zelda_game;
    sfSprite *sprite_touches;
    sfSprite *sprite_fond_go;
    sfSprite *sprite_dielink;
    sfSprite *sprite_quit_go;
    sfSprite *sprite_quit_surbr_go;
    sfSprite *sprite_end_win;
    sfSprite *sprite_fond_noir_win;
    sfTexture *texture_bombatack;
    sfTexture *texture_alien;
    sfTexture *texture_cinem1;
    sfTexture *texture_cinem2;
    sfTexture *texture_cinem3;
    sfTexture *texture_zelda;
    sfTexture *texture_touches;
    sfTexture *texture_fond_go;
    sfTexture *texture_dielink;
    sfTexture *texture_end_win;
    sfVector2f pos_alien;
    sfVector2f pos_alien_2;
    sfVector2f pos_alien_3;
    sfVector2f pos_alien_4;
    sfVector2f pos_alien_5;
    sfVector2f pos_alien_6;
    sfVector2f pos_alien_7;
    sfVector2f pos_alien_8;
    sfVector2f pos_alien_9;
    sfVector2f pos_alien_10;
    sfVector2f pos_bombattack;
    sfVector2f pos_bombattack_2;
    sfVector2f pos_bombattack_3;
    sfVector2f pos_bombattack_4;
    sfVector2f pos_bombattack_5;
    sfVector2f pos_bombattack_6;
    sfVector2f pos_bombattack_7;
    sfVector2f pos_bombattack_8;
    sfVector2f pos_cinem1;
    sfVector2f pos_cinem2;
    sfVector2f pos_cinem3;
    sfVector2f pos_zelda;
    sfVector2f pos_zelda_game;
    sfVector2f pos_touches;
    sfVector2f pos_dielink;
    sfVector2f pos_fond_go;
    sfVector2f pos_quit_go;
    sfVector2f pos_quit_surbr_go;
    sfVector2f pos_end_win;
    sfVector2f pos_fond_noir_win;
    sfIntRect rect_alien;
    sfIntRect rect_alien_2;
    sfIntRect rect_alien_3;
    sfIntRect rect_alien_4;
    sfIntRect rect_alien_5;
    sfIntRect rect_alien_6;
    sfIntRect rect_alien_7;
    sfIntRect rect_alien_8;
    sfIntRect rect_alien_9;
    sfIntRect rect_alien_10;
    float seconds_alien;
    float seconds_alien_2;
    float seconds_alien_3;
    float seconds_alien_4;
    float seconds_alien_5;
    float seconds_alien_6;
    float seconds_alien_7;
    float seconds_alien_8;
    float seconds_alien_9;
    float seconds_alien_10;
    sfTime time_alien;
    sfTime time_alien_2;
    sfTime time_alien_3;
    sfTime time_alien_4;
    sfTime time_alien_5;
    sfTime time_alien_6;
    sfTime time_alien_7;
    sfTime time_alien_8;
    sfTime time_alien_9;
    sfTime time_alien_10;
    sfClock *clock_alien;
    sfClock *clock_alien_2;
    sfClock *clock_alien_3;
    sfClock *clock_alien_4;
    sfClock *clock_alien_5;
    sfClock *clock_alien_6;
    sfClock *clock_alien_7;
    sfClock *clock_alien_8;
    sfClock *clock_alien_9;
    sfClock *clock_alien_10;
}gameplay;


void create_from_file(prcpl *ecr_prcpl, move_p *mvc, gameplay *game);
void create_sprite(prcpl *ecr_prcpl, move_p *mvc, gameplay *game);
void create_texture(prcpl *ecr_prcpl, move_p *mvc, gameplay *game);
void event_function(prcpl *ecr_prcpl, display *window);
void render_draw_sprite(prcpl *ecr_prcpl, display *window, move_p *mvc,
gameplay *game);
void set_pos(prcpl *ecr_prcpl, move_p *mvc, gameplay *game);
void sprite_pos(prcpl *ecr_prcpl, move_p *mvc, gameplay *game);
void texture_rect(prcpl *ecr_prpl, move_p *mvc, gameplay *game);
void animation_logo(prcpl *ecr_prcpl);
sfVector2f click_quit(sfMouseButtonEvent interaction, sfVector2f pos_quit,
display *window);
sfVector2f click_play(sfMouseButtonEvent interaction, sfVector2f pos_quit,
prcpl *ecr_prcpl, display *window);
void mouse_click(prcpl *ecr_prcpl, display *window, gameplay *game);
void interaction_button(prcpl *ecr_prcpl, display *window, gameplay *game);
void set_elements(prcpl *ecr_prcpl, display *window, move_p *mvc,
gameplay *game);
void animation_mvright(move_p *mvc);
void move_p_right(move_p *mvc, prcpl *ecr_prcpl, display *window,
gameplay *game);
void move_p_left(move_p *mvc, prcpl *ecr_prcpl, display *window,
gameplay *game);
void move_p_front(move_p *mvc, prcpl *ecr_prcpl, display *window,
gameplay *game);
void move_p_back(move_p *mvc, prcpl *ecr_prcpl, display *window,
gameplay *game);
void animation_mvleft(move_p *mvc);
void animation_mvfont(move_p *mvc);
void animation_mvback(move_p *mvc);
void animation_attack_right(move_p *mvc, display *window);
void animation_attack_left(move_p *mvc, display *window);
void animation_attack_front(move_p *mvc, display *window);
void animation_attack_back(move_p *mvc, display *window);
void create_from_file_2(move_p *mvc, gameplay *game,  prcpl *ecr_prcpl);
void set_draw_zelda(display *window, move_p *mvc);
void set_rect(prcpl *ecr_prcpl, move_p *mvc, gameplay *game);
void set_attack(display *window, move_p *mvc);
void set_draw_attack(display *window, move_p *mvc);
void animation_alien(gameplay *game);
void animation_alien_2(gameplay *game);
void animation_alien_3(gameplay *game);
void animation_alien_4(gameplay *game);
void animation_alien_5(gameplay *game);
void attack_bomb_1(gameplay *game, display *window);
void sprite_pos_2(move_p *mvc, gameplay *game);
void sprite_pos_3(move_p *mvc, gameplay *game, prcpl *ecr_prcpl);
void create_sprite_2(gameplay *game);
void create_sprite_3(move_p *mvc, gameplay *game);
void create_sprite_4(gameplay *game, prcpl *ecr_prcpl, move_p *mvc);
void create_texture_2(prcpl *ecr_prcpl, move_p *mvc, gameplay *game);
void create_texture_3(gameplay *game, prcpl *ecr_prcpl, move_p *mvc);
void set_pos_2(prcpl *ecr_prcpl, move_p *mvc, gameplay *game);
void set_pos_3(prcpl *ecr_prcpl, move_p *mvc, gameplay *game);
void draw_cinematique(prcpl *ecr_prcpl, display *window, move_p *mvc,
gameplay *game);
void set_collision_1(gameplay *game, display *window, move_p *mvc);
void set_collision_2(gameplay *game, display *window, move_p *mvc);
void set_collision_3(gameplay *game, display *window, move_p *mvc);
void set_collision_4(gameplay *game, display *window, move_p *mvc);
void set_collision_5(gameplay *game, display *window, move_p *mvc);
void set_collision_6(gameplay *game, display *window, move_p *mvc);
void set_collision_7(gameplay *game, display *window, move_p *mvc);
void set_collision_8(gameplay *game, display *window, move_p *mvc);
void set_collision_9(gameplay *game, display *window, move_p *mvc);
void set_collision_10(gameplay *game, display *window, move_p *mvc);
void die_link(move_p *mvc, gameplay *game, display *window, prcpl *ecr_prcpl);
void set_bool(display *window, move_p *mvc);
sfVector2f click_quit_go(sfMouseButtonEvent interaction, sfVector2f pos_quit,
display *window);
void create_sprite_5(gameplay *game);
void die_alien(gameplay *game, display *window);
void die_alien_2(gameplay *game, display *window);
void die_alien_3(gameplay *game, display *window);
void die_alien_4(gameplay *game, display *window);
void die_alien_5(gameplay *game, display *window);
void die_alien_6(gameplay *game, display *window);
void die_alien_7(gameplay *game, display *window);
void die_alien_8(gameplay *game, display *window);
void die_alien_9(gameplay *game, display *window);
void die_alien_10(gameplay *game, display *window);
void attack_bomb_2(gameplay *game, display *window);
void get_victory(gameplay *game, move_p *mvc, display *window);
void create_texture_4(gameplay *game, prcpl *ecr_prcpl, move_p *mvc);
void create_texture_5(gameplay *game, prcpl *ecr_prcpl, move_p *mvc);
void create_texture_6(gameplay *game, prcpl *ecr_prcpl, move_p *mvc);